### ISSUE TITLE
Suggestion: Use a long-lived authorization Heroku token instead?

### ISSUE THREAD

**Issue by philgyford** [kbaum/heroku-database-backups#22]
The current way of creating the `HEROKU_API_KEY`:

```
heroku config:add HEROKU_API_KEY=`heroku auth:token` -a my-database-backups
```

creates a token that quietly expires in one year. I just noticed my backups stopped running a month ago!

Is it worth adding to the README that you could do this instead, to create a long-lived authorization token:

```
heroku config:set HEROKU_API_KEY=`heroku authorizations:create -S -d my-database-backups` -a my-database-backups
```

**Comment by kbaum** [comment]
Sure. Happy to pull in something like that. I think it’s worth using something like dead mans snitch for your database backups.
