### ISSUE TITLE
[question] how to access or restore from the backup?

### ISSUE THREAD

**Issue by MyraGul** [kbaum/heroku-database-backups#35]
Hi! 

I have a few questions:

- For every time we run this script, a new file will be stored in S3, right? It wont overwrite the old one?
- Once the file is saved in S3. How do we access its content? For example, what if I want to use a backup and restore it into another heroku app? Any idea on this? because wont the file be encrypted in the S3 bucket?

Thank you.

**Comment by MyraGul** [comment]
@kbaum any idea on the above^

**Comment by kbaum** [comment]
Hi @MyraGul. It's been a while and I'm not using Heroku on a daily basis but you can expose a temporary obfuscated url in s3. I Unfortunately I think you would need to then access that file through the url and decrypt and decompress. Then you can expose it again through another temp obfuscated url and point heroku restore at this file. I can't remember the exact steps but you only need a publicly available pg dump to restore on Heroku.
