### ISSUE TITLE
Invalid argument: "-e"

### ISSUE THREAD

**Issue by rickharrison** [kbaum/heroku-database-backups#6]
This might be an error with the migration over to the new pgbackups. I am getting this error installing the aws cli.

**Comment by sprytechies** [comment]
any solution for this yet?

**Comment by sprytechies** [comment]
Removing -e worked, but I am not sure what is it for. Care to explain?

**Comment by CullenShane** [comment]
I am also getting this error.  The -e option just removes the oldest database backup if there isn't a slot available.  Maybe it does that by default now?
