### ISSUE TITLE
Small depreciation warning

### ISSUE THREAD

**Issue by aug-riedinger** [kbaum/heroku-database-backups#9]
Since the readme explains everything to move to the newest heroku pgbackup strategy, I thought I'd mention a depreciation warning I got:

```
heroku addons:add scheduler -a myapp-backups
WARNING: `heroku addons:add` has been deprecated. Please use `heroku addons:create` instead.
```

I can PR if desired!

**Comment by kbaum** [comment]
Good call!  PR would be great!
